---
openapi: 3.1.0
components:
  schemas:
    InfoResponse:
      type: object
      properties:
        name:
          type: string
          description: The identificative name of the deployed application
          examples:
            - pagopa-fdr-technical-support
        version:
          type: string
          description: The current version of the deployed application
          examples:
            - 1.2.3
        environment:
          type: string
          description: The current environment where the application is deployed
          examples:
            - dev
        description:
          type: string
          description: The descriptive information related to the info response
          examples:
            - FDR Technical Support
    LocalDate:
      type: string
      format: date
      examples:
        - 2022-03-10
    ProblemJson:
      type: object
      properties:
        title:
          type: string
          description: "A short, summary of the problem type. Written in english and\
            \ readable for engineers (usually not suited for non technical stakeholders\
            \ and not localized); example: Service Unavailable"
        status:
          type: integer
          format: int32
          description: The HTTP status code generated by the origin server for this
            occurrence of the problem.
          examples:
            - 200
          maximum: 600
          minimum: 100
        details:
          type: string
          description: A human readable explanation specific to this occurrence of
            the problem.
          examples:
            - There was an error processing the request
  responses:
    ErrorResponse400:
      description: Default app exception for status 400
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
    ErrorResponse404:
      description: Default app exception for status 404
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
    ErrorResponse500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemJson"
  securitySchemes:
    ApiKey:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
info:
  description: |
    Technical support API for FDR (aka "Flussi di Rendicontazione")

    ## OPERATIONAL ERROR CODES

    <details><summary>Details</summary>
    NAME | CODE | ERROR MESSAGE TEMPLATE | DESCRIPTION
    - | - | - | -
    **FDR-0400** | *DATE_BAD_REQUEST* | Bad request | An error occurred while validating the provided dates
    **FDR-0404** | *FLOW_NOT_FOUND* | No flow found | An error occurred during the search of flow. The needed <br>flow does not exists in current environment
    **FDR-1404** | *FLOW_NOT_FOUND_CLIENT* | No flow found | An error occurred during the search of flow. The needed <br>flow was not found
    **FDR-1401** | *UNAUTHORIZED_CLIENT* | An unexpected error has occurred. Please contact support | An error occurred while invoking external services
    **FDR-0500** | *ERROR* | An unexpected error has occurred. Please contact support | An error occurred during computation. This could be <br>caused by an applicative error and it is probably required <br>to open an issue.
    **FDR-0400** | *BAD_REQUEST* | Bad request | A generic 'Bad Request' error is occurred during request <br>validation
    **FDR-0401** | *BAD_REQUEST_INPUT_JSON* | bad.request.inputJson | A generic error occurred during execution of request <br>syntactic validation
    **FDR-0402** | *BAD_REQUEST_INPUT_JSON_INSTANT* | bad.request.inputJson.instant | An error occurred during execution of request syntactic <br>validation, in particular regarding the analysis of <br>date values
    **FDR-0403** | *BAD_REQUEST_INPUT_JSON_ENUM* | bad.request.inputJson.enum | An error occurred during execution of request syntactic <br>validation, in particular regarding the analysis of <br>enumerative values
    **FDR-0404** | *BAD_REQUEST_INPUT_JSON_DESERIALIZE_<br>ERROR* | bad.request.inputJson.deserialize | An error occurred during execution of deserialization <br>of request from a JSON string
    **FDR-0405** | *BAD_REQUEST_INPUT_JSON_NON_VALID_<br>FORMAT* | bad.request.inputJson.notValidJsonFormat | An error occurred during execution of analysis of JSON <br>request, in particular regarding its format
    **FDR-0406** | *INVALID_FILE_TYPE* | Invalid file type specified. | An error occurred while validating the provided file <br>type. The file must be of type Xml or Json
  termsOfService: https://www.pagopa.gov.it/
  title: fdr-techical-support API
  version: 1.0.14
servers:
  - url: http://localhost:8080
    description: Localhost base URL
  - url: "https://{host}/technical-support/api/v1"
    description: Base URL
    variables:
      host:
        description: Environment host
        enum:
          - api.dev.platform.pagopa.it
          - api.uat.platform.pagopa.it
          - api.platform.pagopa.it
        default: api.dev.platform.pagopa.it
tags:
  - name: Info
    description: Info operations
  - name: Organization
    description: APIs for inspecting creditor institution usage of flows
  - name: PSP
    description: APIs for inspecting PSP usage of flows
paths:
  /info:
    get:
      summary: Health-check
      description: |-
        ## Description:
        Get health check and deployment-related information
      operationId: InfoController_healthCheck
      tags:
        - Info
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InfoResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              example: '...'
              schema:
                $ref: "#/components/schemas/ProblemJson"
  /organizations/{organizationId}/flows/{flowId}:
    get:
      summary: '...'
      description: |-
        ## Description:
        ...
      operationId: OrganizationsController_getRevisions
      tags:
        - Organization
      parameters:
        - name: flowId
          in: path
          required: true
          schema:
            type: string
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
        - name: dateFrom
          in: query
          schema:
            $ref: "#/components/schemas/LocalDate"
        - name: dateTo
          in: query
          schema:
            $ref: "#/components/schemas/LocalDate"
      responses: { }
  /organizations/{organizationId}/psps/{pspId}/download:
    get:
      summary: '...'
      description: |-
        ## Description:
        ...
      operationId: OrganizationsController_getDownloads
      tags:
        - Organization
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
        - name: pspId
          in: path
          required: true
          schema:
            type: string
        - name: date
          in: query
          schema:
            $ref: "#/components/schemas/LocalDate"
      responses: { }
  /organizations/{organizationId}/psps/{pspId}/flows/{flowId}/revisions/{revision}:
    get:
      summary: '...'
      description: |-
        ## Description:
        ...
      operationId: OrganizationsController_getFlow
      tags:
        - Organization
      parameters:
        - name: flowId
          in: path
          required: true
          schema:
            type: string
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
        - name: pspId
          in: path
          required: true
          schema:
            type: string
        - name: revision
          in: path
          required: true
          schema:
            type: string
        - name: dateFrom
          in: query
          schema:
            $ref: "#/components/schemas/LocalDate"
        - name: dateTo
          in: query
          schema:
            $ref: "#/components/schemas/LocalDate"
        - name: fileType
          in: query
          schema:
            type: string
      responses: { }
  /organizations/{organizationId}/psps/{pspId}/upload:
    get:
      summary: '...'
      description: |-
        ## Description:
        ...
      operationId: OrganizationsController_getUploads
      tags:
        - Organization
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
        - name: pspId
          in: path
          required: true
          schema:
            type: string
        - name: date
          in: query
          schema:
            $ref: "#/components/schemas/LocalDate"
      responses: { }
  /psps/{pspId}:
    get:
      summary: '...'
      description: |-
        ## Description:
        ...
      operationId: PSPController_searchFlowByPsp
      tags:
        - PSP
      parameters:
        - name: pspId
          in: path
          required: true
          schema:
            type: string
        - name: dateFrom
          in: query
          schema:
            $ref: "#/components/schemas/LocalDate"
        - name: dateTo
          in: query
          schema:
            $ref: "#/components/schemas/LocalDate"
        - name: flowId
          in: query
          schema:
            type: string
        - name: organizationId
          in: query
          schema:
            type: string
      responses: { }
  /psps/{pspId}/iur/{iur}:
    get:
      summary: '...'
      description: |-
        ## Description:
        ...
      operationId: PSPController_searchFlowByPspAndIur
      tags:
        - PSP
      parameters:
        - name: iur
          in: path
          required: true
          schema:
            type: string
        - name: pspId
          in: path
          required: true
          schema:
            type: string
        - name: dateFrom
          in: query
          schema:
            $ref: "#/components/schemas/LocalDate"
        - name: dateTo
          in: query
          schema:
            $ref: "#/components/schemas/LocalDate"
      responses: { }
  /psps/{pspId}/iuv/{iuv}:
    get:
      summary: '...'
      description: |-
        ## Description:
        ...
      operationId: PSPController_searchFlowByPspAndIuv
      tags:
        - PSP
      parameters:
        - name: iuv
          in: path
          required: true
          schema:
            type: string
        - name: pspId
          in: path
          required: true
          schema:
            type: string
        - name: dateFrom
          in: query
          schema:
            $ref: "#/components/schemas/LocalDate"
        - name: dateTo
          in: query
          schema:
            $ref: "#/components/schemas/LocalDate"
      responses: { }
