microservice-chart:
  namespace: "fdr"
  image:
    repository: ghcr.io/pagopa/pagopa-fdr-technical-support
    tag: '1.0.14'
  readinessProbe:
    httpGet:
      path: /q/health/ready
      port: 8080
    initialDelaySeconds: 8
    failureThreshold: 10
    periodSeconds: 2
  livenessProbe:
    httpGet:
      path: /q/health/live
      port: 8080
    initialDelaySeconds: 8
    failureThreshold: 10
    periodSeconds: 2
  envConfig:
    APP_ENVIRONMENT: "uat"
    TZ: "Europe/Rome"
    OTEL_ENDPOINT: "http://otel-collector.elastic-system.svc.cluster.local:4317"
    FDR_ENDPOINT: "https://api.uat.platform.pagopa.it/fdr/service-internal/v1"
    LOG_LEVEL: "DEBUG"
    RE_EVENTS_DATE_RANGE_LIMIT: "7"
  envFieldRef:
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  secretProvider:
    create: true
    envSecrets:
      MONGODB_CONNECTION_STRING: "mongodb-re-connection-string"
      FDR_TABLE_STORAGE_CONN_STRING: "fdr-sa-connection-string"
      FDR_SUBSCRIPTION_KEY: "fdr-internal-product-subscription-key"
    keyvault:
      name: "pagopa-u-fdr-kv"
      tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  tmpVolumeMount:
    create: true
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "768Gi"
      cpu: "400m"
  autoscaling:
    enable: false
  deployment:
    replicas: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  serviceAccount:
    name: "fdr-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  serviceMonitor:
    create: true
    endpoints:
      - interval: 5s
        targetPort: 8080
        path: /q/metrics
  service:
    create: true
  ingress:
    create: true
    host: "weuuat.fdr.internal.uat.platform.pagopa.it"
    path: /pagopa-fdr-technical-support-service/(.*)
  canaryDelivery:
    create: false
